---

- name: Download TransDecoder source
  get_url:
    url: "{{ TRANS_URL }}"
    dest: "/tmp/TransDecoder-3.0.1.tar.gz"

- name: Unpack source code
  unarchive:
    src: "/tmp/TransDecoder-3.0.1.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Configure TransDecoder
  command: ./configure
  args:
    chdir: "/tmp/TransDecoder-3.0.1"

- name: Build TransDecoder
  make:
    chdir: "/tmp/TransDecoder-3.0.1"

- name: Install TransDecoder
  make:
    chdir: "/tmp/TransDecoder-3.0.1"
    target: install

- name: Move executables to path
  copy:
    src: "/tmp/TransDecoder-3.0.1/{{ item }}"
    dest: "/usr/local/{{ item }}"
    remote_src: yes
  with_items:
    - "TransDecoder.LongOrfs"
    - "TransDecoder.Predict"

- name: Cleanup
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/tmp/TransDecoder-3.0.1.tar.gz"
    - "/tmp/TransDecoder-3.0.1"
